### ISSUE TITLE
 return runtime.deserialize_cuda_engine(f.read()) ERROR

### ISSUE THREAD

**Issue by Dawnlnz** [darkknightzh/TensorRT_pytorch#2]
Traceback (most recent call last):
  File "main.py", line 180, in <module>
    engine_data = load_engine(args.engine_file_path)
  File "main.py", line 136, in load_engine
    return runtime.deserialize_cuda_engine(f.read())
TypeError: runtime_deserialize_legacy() missing 1 required positional argument: 'size'

**Comment by darkknightzh** [comment]
Sorry that I did not have this problem. 
The TensorRT version I use is 5.1.5. I am not sure the code can work on other versions.
Sorry.

**Comment by Dawnlnz** [comment]
My TensorRT is 5.1.5. I will try in other ways.Thank you.

**Comment by Dawnlnz** [comment]
> Sorry that I did not have this problem.
> The TensorRT version I use is 5.1.5. I am not sure the code can work on other versions.
> Sorry.

My TensorRT is 5.1.5. I will try in other ways.
Thank you.
